name: Manage Repository

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'The name of the repository to create or delete'
        required: true
        default: 'new-repo'
      action:
        description: 'Action to perform: create or delete'
        required: true
        type: choice
        default: 'create'
        options:
          - create
          - delete

jobs:
  manage-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Install GitHub CLI
      run: |
        sudo apt-get install -y gh
        gh auth login --with-token <<< "${{ secrets.TOKEN }}"
    - name: Check action type
      id: action_type
      run: echo "ACTION_TYPE=${{ github.event.inputs.action }}" >> $GITHUB_OUTPUT

    - name: Create Repository
      if: ${{ steps.action_type.outputs.ACTION_TYPE == 'create' }}
      run: |
        gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /orgs/FathAllaTechOps/repos \
          -f name="${{ github.event.inputs.repository_name }}" \
          -f description="Repository created by workflow" \
          -F private=false \
          -F has_issues=true \
          -F has_projects=true \
          -F has_wiki=true

    - name: Delete Repository
      if: ${{ steps.action_type.outputs.ACTION_TYPE == 'delete' }}
      run: |
        gh api --method DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/FathAllaTechOps/${{ github.event.inputs.repository_name }}
